apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: do5ewmkmg-python
  janus-idp.io/tekton: do5ewmkmg-python
  backstage.io/kubernetes-id: do5ewmkmg-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: do5ewmkmg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
